[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://robpins.me/*"
  to = "https://hub.robpins.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.robpins.me/*"
  to = "https://hub.robpins.me/:splat"
  status = 301
  force = true
